### ISSUE TITLE
"RectangleCell in class RectangleCell cannot be applied to given types" and custom nodes

### ISSUE THREAD

**Issue by gipic** [sirolf2009/fxgraph#1]
Thank you for sharing this library.
When I copy the code, there is an error on the constructor of RectangleCell and TriangleCell.
I have fixed it passing an empty string "" to the constructor.
Example from this:
final ICell cellA = new RectangleCell(); // Or final ICell cellD = new TriangleCell();
to
final ICell cellA = new RectangleCell(""); // Or final ICell cellD = new TriangleCell("");
Is it normal or I have installed this library not correctly?
Thanks.

**Comment by sirolf2009** [comment]
You have installed the library correctly, you didn't copy the code correctly (though that's kind of my fault).
In v0.0.2 the cells require a string in their constructor. Those string were originally used as ID's for the graph. I've since then changed that so that the graphs just use pointers as ID's, but that hasn't been released yet. 
If you look at the README there's an example that uses strings. The README also refers you to MainApp for a complete example, but I've updated the MainApp to not take string params. So really I shouldn't have send you to the MainApp class.
I'll just release v0.0.3 and I'll update the README, that should sync everything up.

**Comment by gipic** [comment]
Thanks for reply.
Is there a way to put a name/string inside a Cell (Node)? I have thought that the string passed to the Cell constructor was related to this feature.

**Comment by sirolf2009** [comment]
The default cells are resizable because they're basically there to show off the possible features. To customize features like resizing or drawing strings in them, you should implement your own node with the features you want. Here's an edited version of RectangleCell to get you started
```java
package com.fxgraph.cells;

import com.fxgraph.graph.Graph;

import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;
import javafx.geometry.Pos;
import javafx.scene.layout.Region;
import javafx.scene.layout.StackPane;
import javafx.scene.paint.Color;
import javafx.scene.shape.Rectangle;
import javafx.scene.text.Text;

public class RectangleCell extends AbstractCell {

	private final StringProperty textProperty;

	public RectangleCell(String text) {
		this.textProperty = new SimpleStringProperty(text);
	}

	@Override
	public Region getGraphic(Graph graph) {
		final Rectangle view = new Rectangle(50, 50);

		view.setStroke(Color.DODGERBLUE);
		view.setFill(Color.DODGERBLUE);

		final StackPane pane = new StackPane(view);
		pane.setAlignment(Pos.CENTER);
		pane.setPrefSize(50, 50);
		view.widthProperty().bind(pane.prefWidthProperty());
		view.heightProperty().bind(pane.prefHeightProperty());

		final Text text = new Text();
		text.textProperty().bind(textProperty);
		pane.getChildren().add(text);
		return pane;
	}

}
```

**Comment by gipic** [comment]
Thank you very much!! Very helpful!
